### ISSUE TITLE
nios_a_record module - KeyError: 'old_ipv4addr'

### ISSUE THREAD

**Issue by laurentprevost** [infobloxopen/infoblox-ansible#79]
Hello there,

I am encountering an issue with the module `infoblox.nios_modules.nios_a_record`. When I try to reserve the `nios_next_ip` I got the following error message:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'old_ipv4addr'
fatal: [localhost]: FAILED! => changed=false
  module_stderr: |-
    Shared connection to localhost closed.
  module_stdout: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-tmp-1631884310.097634-29025-204631004031576/AnsiballZ_nios_a_record.py", line 100, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-tmp-1631884310.097634-29025-204631004031576/AnsiballZ_nios_a_record.py", line 92, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-tmp-1631884310.097634-29025-204631004031576/AnsiballZ_nios_a_record.py", line 41, in invoke_module
        run_name='__main__', alter_sys=True)
      File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)
      File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_infoblox.nios_modules.nios_a_record_payload_6eeanwso/ansible_infoblox.nios_modules.nios_a_record_payload.zip/ansible_collections/infoblox/nios_modules/plugins/modules/nios_a_record.py", line 179, in <module>
      File "/tmp/ansible_infoblox.nios_modules.nios_a_record_payload_6eeanwso/ansible_infoblox.nios_modules.nios_a_record_payload.zip/ansible_collections/infoblox/nios_modules/plugins/modules/nios_a_record.py", line 173, in main
      File "/tmp/ansible_infoblox.nios_modules.nios_a_record_payload_6eeanwso/ansible_infoblox.nios_modules.nios_a_record_payload.zip/ansible_collections/infoblox/nios_modules/plugins/module_utils/api.py", line 275, in run
      File "/tmp/ansible_infoblox.nios_modules.nios_a_record_payload_6eeanwso/ansible_infoblox.nios_modules.nios_a_record_payload.zip/ansible_collections/infoblox/nios_modules/plugins/module_utils/api.py", line 556, in get_object_ref
    KeyError: 'old_ipv4addr'
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

The configuration I used was this:

```yaml
- name: Add A Record (reserve ip)
  infoblox.nios_modules.nios_a_record:
    name: "{{ infoblox_host_fqdn }}"
    view: "{{ infoblox_default_view }}"
    ipv4:
      nios_next_ip: "{{ infoblox_lookup_vlan.cidr }}"
    state: present
    provider: "{{ nios_provider }}"
```

with the values:
- infoblox_host_fqdn=a.b.c (as an example)
- infoblox_default_view=default
- infoblox_lookup_vlan.cidr=10.20.30.40 (as an example)
- nios_provider= contains the proper credentials

I am running:
- Ansible 4.5.0
- Ansible Core 2.12.5
- Ansible Infoblox 1.1.1
- Infoblox Client 0.5.0
- Python 3.6.8

```
ansible [core 2.11.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/.../.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  ansible collection location = /.../ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.1
  libyaml = True
```

I found a workaround to make it working by adding the `old_ipv4addr` parameter into the `ipv4/ipv4addr` elements in the task configuration:

```yaml
- name: Add A Record (reserve ip)
  infoblox.nios_modules.nios_a_record:
    name: "{{ infoblox_host_fqdn }}"
    view: "{{ infoblox_default_view }}"
    ipv4:
      nios_next_ip: "{{ infoblox_lookup_vlan.cidr }}"
      old_ipv4addr: 0.0.0.0 # <- Workaround
    state: present
    provider: "{{ nios_provider }}"
```

**Comment by anagha-infoblox** [comment]
Hi @laurentprevost,
This issue has been resolved with the following Pull Request- https://github.com/infobloxopen/infoblox-ansible/pull/96 .
Hence, closing the issue. Please verify the same.
